- chevah/compat/testing/filesystem.py
- chevah/compat/testing/mockup.py
- chevah/compat/testing/testcase.py
- chevah/compat/tests/elevated/test_system_users.py
- chevah/compat/tests/normal/test_avatar.py
- chevah/compat/tests/normal/test_system_users.py
- pavement.py
- paver.conf
- paver.sh
- release-notes.rst
- setup.py
Scope
=====
This update the code to run on Alpine slave.
Changes
=======
Update paver.sh to recognize alpine.
For now PAM test is skipped and for osgroups we ignore duplicate groups.
As a drive-by change I have updated os_version detection in the test case to get the AIX version.
check that changes make sense.
Run running test on python-package you might want to use this branch instead of master.
> [#4330] Add support for Alpine Linux.

- chevah/compat/administration.py
- chevah/compat/testing/__init__.py
- chevah/compat/testing/mockup.py
- chevah/compat/testing/testcase.py
- chevah/compat/tests/elevated/__init__.py
- chevah/compat/tests/normal/testing/test_testcase.py
- release-notes.rst
- setup.py
Scope
=====
This fix the cleanup code which should call the cleanup in reverse order.
Changes
=======
Run in reverse.
As a drive by, I have start moving away from python-future as it is bad :) and just use unicode_literals
reviewers: @lgheorghiu 
Not much to test. Here for compliance as there is no one else to review
> [#4353] Run cleanup in reverse order as they are added.

- chevah/compat/nt_filesystem.py
- chevah/compat/tests/normal/test_filesystem.py
- release-notes.rst
- setup.py
Scope
=====
getAttributes will success on Windows when link is broken, but will fail on Unix.
This unifies the behaviour.
Changes
=======
For windows, check that path exists before getting attributes
reviewers: @bgola 
check that changes make sense
> [#4468] Fix getAttributes on Windows for broken links.

- chevah/compat/testing/assertion.py
- chevah/compat/testing/testcase.py
- chevah/compat/tests/normal/test_testing.py
- release-notes.rst
- setup.py
Scope
=====
This adds an option to ignore certain threads during the tearDown.
Changes
=======
Added a class attribute to ChevahTestCase that can be overridden by subclasses / other test cases.
reviewers: @adiroiban 
Please check if it makes sense. Thanks!
> [#4588] Add option to except thread names on ChevahTestCase tearDown.

- .gitignore
- chevah/compat/testing/testcase.py
- chevah/compat/tests/normal/test_filesystem.py
- chevah/compat/tests/normal/testing/test_testcase.py
- paver.conf
- paver.sh
- release-notes.rst
- setup.py
Scope
=====
This is an import for some changes which were done in chevah/server but which should have been here.
Changes
=======
Use a small timeout instead of None for reactor iteration.
As a drive by I moved more functions to compat and wrote tests, as in chevah/server they were just used, but without dedicated tests.
reviewers: @bgola 
check that changes make sense
thanks
> [#4753] Always iterate the reactor with timeout.

- chevah/compat/interfaces.py
- chevah/compat/nt_filesystem.py
- chevah/compat/posix_filesystem.py
- chevah/compat/testing/conditionals.py
- chevah/compat/testing/filesystem.py
- chevah/compat/testing/testcase.py
- chevah/compat/tests/mixin/filesystem.py
- chevah/compat/tests/normal/test_capabilities.py
- chevah/compat/tests/normal/test_filesystem.py
- pavement.py
- release-notes.rst
- setup.py
Scope
=====
This fix tha path handling to work with UNC paths and be able to work with symbolic links to Windows Shares.
Changes
=======
Add support for UNC.
Links to Windows Shares always exist.
This is just to check that compat is green on the supported platform.
Also check that the supported platforms are marked as "Required" in github.
Thanks!
> [#4681] Add support for UNC and links to Windows Shares.

- chevah/compat/avatar.py
- chevah/compat/interfaces.py
- chevah/compat/nt_filesystem.py
- chevah/compat/nt_users.py
- chevah/compat/posix_filesystem.py
- chevah/compat/testing/assertion.py
- chevah/compat/testing/conditionals.py
- chevah/compat/testing/testcase.py
- chevah/compat/tests/normal/test_avatar.py
- chevah/compat/tests/normal/test_filesystem.py
- chevah/compat/tests/normal/testing/test_assertion.py
- chevah/compat/tests/normal/testing/test_testcase.py
- chevah/compat/unix_filesystem.py
- chevah/compat/unix_users.py
- pavement.py
- release-notes.rst
- setup.py
Scope
=====
This adds support for creating virtual folders (virtual segments) on top of the normal available segments.
This will work like a symlink and is available for both locked and unlocked filesystems.
Changes
=======
Add support for virtual folders and error handling when trying to mutate a virtual folder.
The filesystem handling is part of chevah/compat so we have this change here... but the main tests will be done in a server dedicated PR
This PR is big as there are a lot of tests.
> [#4969] Add support for virtual folders.

- chevah/compat/nt_filesystem.py
- chevah/compat/posix_filesystem.py
- chevah/compat/tests/normal/test_filesystem.py
- pavement.py
- paver.conf
- release-notes.rst
- setup.py
Scope
=====
This updates the compat code to add filename when OSError has no filename.
For example on Windows.
Changes
=======
Refactor the code to add filename.
As a drive by, update the dev env for latest buildbot with local passwords.
We can use this PR to update the python package.
Please check what Python-package should I use.
> [#5072] Add filename to OSError.

- chevah/compat/posix_filesystem.py
- chevah/compat/testing/testcase.py
- chevah/compat/tests/elevated/test_filesystem.py
- chevah/compat/tests/normal/test_filesystem.py
- paver.conf
- paver.sh
- release-notes.rst
- setup.py
Scope
=====
This updates the folder iteraction fuction to return file attributes, instead of just names.
In this way, you don't need an extra call to get the attributes for each member.
Changes
=======
Convert scandir attributes to FileAttributes, update test.
Not much to review. Hope all slaves are ok and we can add arm64 works.
> [#5082] Return attributes from folder iterations.

- chevah/compat/nt_filesystem.py
- chevah/compat/testing/testcase.py
- chevah/compat/tests/normal/test_filesystem.py
- paver.conf
- paver.sh
Scope
=====
On  Windows, default rename fails if destination exists.
But we don't want to fail so that we have the same behaviour on all OS.
Changes
=======
Handle error on rename on Windows and delete the destination
As a drive-by I have also updated the paver.sh and paver.conf
This is more FYI.
> [#5200] Overwrite destination on rename in Windows

- chevah/compat/testing/assertion.py
- chevah/compat/testing/testcase.py
- chevah/compat/tests/normal/test_testing.py
- paver.conf
- paver.sh
- release-notes.rst
- scripts/nose_runner.py
- setup.py
Scope
=====
`compat` tests do not pass with the shorter win OS name, which prevents testing new `python-package` builds successfully on Windows slaves.
Changes
=======
Updated paver stuff from `python-package`.
reviewers: **WIP**
> [#5311] Shorter OS names.

- .travis.yml
- CONTRIBUTING.rst
- README.rst
- brink.conf
- brink.sh
- chevah/compat/tests/normal/test_system_users.py
- pavement.py
Scope
=====
`test_getHomeFolder_posix` fails for chevah/pythia on Travis' macOS.
More at https://travis-ci.com/github/chevah/pythia/jobs/398801185
Changes
=======
Always assume `/Users` on macOS when the user is not `buildslave`.
**Drive-by fixes**:
* Overwrite existing file when unzipping the Python package tarball.
* Added experimental Travis CI.
* Updated brink/pavement stuff from server and pythia, without removing any supported OS.
* Updated README accordingly.
reviewers: @adiroiban 
Please review changes.
> Assume /Users on macOS when not buildslave user.

- .github/workflows/main.yml
- chevah/compat/posix_filesystem.py
- chevah/compat/tests/elevated/test_system_users.py
- chevah/compat/tests/normal/test_filesystem.py
- release-notes.rst
- setup.py
Scope
=====
This fix a critical bug in which path containing single quotes are not handled corretly.
The single quote is replaced for a path separator.
For example, with the old code a path line 
```
/some/O`Reilly/file
was converted in 
/some/O/Reilly/file
```
Changes
=======
Update the path split code and simplify it with explicit regrex escaping.
I have no idea why I have used `%r` there.
reviewers: @danuker 
Check that changes make sense.
For now this is a quick fix as this is urgent
In the future we should start using https://hypothesis.readthedocs.io/en/latest/index.html for unit testing in this low level libraries so that we can generate all possible characters and make sure path splinting works for them.
> Fix path split for single quotes.

- .github/workflows/docker.yml
- .github/workflows/main.yml
- brink.conf
- brink.sh
- chevah/compat/testing/testcase.py
- chevah/compat/tests/normal/testing/test_testcase.py
- pavement.py
- release-notes.rst
- setup.py
Scope
=====
This updates the compat testing helpers to work with latest Twisted that support Python 2.7.
We were using a very old Twisted version which was a mix of 12.1 and 15.1
With this change,  any future upgrade to Twisted should not require and update to compat.
Changes
=======
Update the test case.
Move `callCleanup` code fix from chevah/server 
As a drive by, move the static checks to GitHub Actions.
I have also removed the custom skip-ci code as GHA has native support now.
I have also update the brink deps... just in case.
reviewers: @danuker 
FYI.
This will be used in a PR in chevah/server where  will implement Twisted update.
> Update for Twisted 20.3.0

- .github/workflows/docker.yml
- .github/workflows/main.yml
- .github/workflows/static_checks.yaml
- chevah/compat/testing/mockup.py
- chevah/compat/testing/testcase.py
- chevah/compat/tests/normal/testing/test_mockup.py
- chevah/compat/tests/normal/testing/test_testcase.py
- chevah/compat/unix_filesystem.py
- pavement.py
- release-notes.rst
- setup.py
Scope
=====
This add support for calling cleanup based on stacks/layers.
This is used by our chevah/server tests in which we have a shared service layer that is used by multiple tests.
Changes
=======
Add a simple enterCleanup/exitCleanup APi for cleanup layers.
As a drive-by change I have updated the IPv4 and IPv6 mocks to return an IP address and not a hostname.
reviewers: @danuker 
check that changes make sense and they can be used in chevah/server
> Add support for stacked cleanups.

- chevah/compat/nt_filesystem.py
- chevah/compat/nt_service.py
- chevah/compat/posix_filesystem.py
- chevah/compat/testing/testcase.py
- chevah/compat/tests/normal/testing/test_assertion.py
- release-notes.rst
- setup.py
Scope
=====
`ChevahTestCase.assertEqual` now goes inside dicts, lists, tuples, and sets to differentiate Unicode vs. raw string objects.
Changes
=======
Added behavior to `chevah/compat/testing/testcase.py`.
Overrode `unittest` methods named `assertSequenceEqual`, `assertSetEqual`, and `assertDictEqual`.
As a drive-by found a bug where `temp_segments` would return raw strings and not Unicode ones.
reviewers: @adiroiban 
Use assertEquals in various ways.
This PR should have a counterpart in `chevah/server` before merging, which fixes the tests broken (or bugs discovered) by the `compat` changes.
> [#5687] assertEqual checks Unicode vs. strings in collections

- .github/workflows/bare.yml
- .github/workflows/docker.yml
- .github/workflows/lint.yaml
- .github/workflows/main.yml
- README.rst
- brink.conf
- chevah/compat/testing/testcase.py
- chevah/compat/tests/elevated/test_system_users.py
- pavement.py
- release-notes.rst
- setup.py
Scope
=====
Test on all OS'es listed as supported at https://www.sftpplus.com/documentation/sftpplus/trial/ (except Windows version other than 2016/2019).
Fix failing tests on CentOS 5 which impede enabling python-package compat tests, see https://github.com/chevah/python-package/pull/151/checks?check_run_id=3278319527
Fixes #117.
Changes
=======
Test on CentOS 5 and 6 under Docker through GHA.
The above requires cloning sources without `actions/checkout`.
On CentOS 5 there was also an issue with the cert for GitHub servers hosting our releases, so I've switched to using bin.chevah.com in `brink.conf` .
Also test on Ubuntu Server 14.04/16.04, while at it.
**Drive-by fixes**:
* Updated Python modules versions in `pavement.py` to match server repo. …
> Test all supported Linux distributions.

- .github/workflows/bare.yml
- .github/workflows/docker.yml
- brink.conf
- brink.sh
- chevah/compat/interfaces.py
- chevah/compat/nt_filesystem.py
- chevah/compat/posix_filesystem.py
- chevah/compat/testing/conditionals.py
- chevah/compat/testing/mockup.py
- chevah/compat/tests/elevated/__init__.py
- chevah/compat/tests/elevated/test_system_users.py
- chevah/compat/tests/normal/test_filesystem.py
- chevah/compat/tests/normal/testing/test_testcase.py
- chevah/compat/unix_users.py
- release-notes.rst
- setup.py
Scope
=====
Fixes #678 
Fixes #677 
Fixes #115 
We need a custom API to detect if a path is absolute.
And as part of this PR, we might need to add support for handling windows shares as segments.
Changes
=======
As a drive-by I have updated brink.sh and conf.
Also updated the GitHub actions workflow with latest oses.
reviewers: @danuker 
check that changes make sense.
> [#678] Add absolute path API.

- .github/workflows/ci.yaml
- README.rst
- pavement.py
- pyproject.toml
- pytest.ini
- release-notes.rst
- src/chevah_compat/administration.py
- src/chevah_compat/testing/assertion.py
- src/chevah_compat/testing/mockup.py
- src/chevah_compat/testing/testcase.py
- src/chevah_compat/tests/conftest.py
- src/chevah_compat/tests/elevated/conftest.py
- src/chevah_compat/tests/normal/testing/test_testcase.py
Scope
=====
Fixes #709
This add support to run compat tests with `pytest`
`pytest` is the current de-facto test framework for Python and we should start using it as it has many nice features. `nose` and `pynose` are dying.
Changes
=======
Update tests for py3
Add pytest configuration.
Run all the `chevah-compat` tests also with `pytest` not only with `pynose`.
As a drive by, update more code for py3 only.
More of a fyi
1.Normal tests
-----------------
You can now run compat test using `pytest` as either
* `./pythia.sh pytest`
* or just run `pytest` directly via `./build-py3/bin/pytest`
2.Elevated tests
-----------------
There are also the "elevated" tests for OS users that are triggered via `sudo …
> [#709] Add support for pytest 

- .github/workflows/ci.yaml
- pavement.py
- pyproject.toml
- release-notes.rst
- src/chevah_compat/exceptions.py
- src/chevah_compat/interfaces.py
- src/chevah_compat/nt_filesystem.py
- src/chevah_compat/nt_users.py
- src/chevah_compat/posix_filesystem.py
- src/chevah_compat/testing/testcase.py
- src/chevah_compat/tests/__init__.py
- src/chevah_compat/tests/elevated/test_filesystem.py
- src/chevah_compat/tests/elevated/test_system_users.py
- src/chevah_compat/tests/elevated/testing/test_filesystem.py
- src/chevah_compat/tests/normal/testing/test_testcase.py
- src/chevah_compat/unix_capabilities.py
- src/chevah_compat/unix_filesystem.py
- src/chevah_compat/unix_users.py
Scope
=====
Fixes #615
This is a hack to somehow fix a threading issue that we have in chevah/server
Our whole code is not designed for running threads with separate user context.
This is a fix only for Linux... but out customer that use this only use Linux.
Changes
=======
Add support for run in non-blocking mode... so if an I/O operation is blocked, the whole process is not.
Add some unit tests
More of a FYI
The actual testing should be done in chevah/server
The main tests are at https://github.com/chevah/server/pull/6975
> [#615] Add support to reset current process effective user

- codecov.yml
- pyproject.toml
- release-notes.rst
- src/chevah_compat/testing/conditionals.py
- src/chevah_compat/tests/normal/test_system_users.py
- src/chevah_compat/unix_users.py
Scope
=====
Fixes #718
This adds support to authenticate Linux OS users using only PAM as non root.
This is somehow similar to what we get in WIndows.
I am user `chevah` , as long as I get username and password for user `JohnDoe` I can use PAM, as a non root user, to check whether the credentials are valid.
Changes
=======
Add a separeate non-root PAM only method.
The old root PAM method was kept for backward compatibility
Automated tests are complicated... when we autoamtically create OS test users we run as root.
This functionality assumes that you are not root... but if we are not root, we can't automatically add OS users... so we can't do automated tests
I wrote some tests to make sure we don't get unexpected errors for wrong password
--------
onOSVersion was removed as the low-level …
> #718 Allow PAM auth as non root user
